-- MySQL Script generated by MySQL Workbench
-- Tue May 10 11:20:59 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema security_exam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `security_exam` ;

-- -----------------------------------------------------
-- Schema security_exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `security_exam` DEFAULT CHARACTER SET utf8 ;
USE `security_exam` ;

-- -----------------------------------------------------
-- Table `security_exam`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_exam`.`users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `activation_key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `activation_key_UNIQUE` (`activation_key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security_exam`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_exam`.`admins` (
  `admin_id` INT NOT NULL COMMENT '	',
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `active` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security_exam`.`gifs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_exam`.`gifs` (
  `gif_id` INT NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `uploaded` DATETIME NOT NULL,
  `pending` TINYINT(1) NOT NULL,
  `gifscol` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`gif_id`),
  UNIQUE INDEX `src_UNIQUE` (`source` ASC),
  INDEX `fk_gifs_users_idx` (`user_id` ASC),
  INDEX `fk_gifs_admins1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_gifs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_exam`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gifs_admins1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `security_exam`.`admins` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
